version: "3"

vars:
  APP_NAME: "LeviLauncher"
  BIN_DIR: "bin"

tasks:
  build:
    summary: Builds the CLI application
    cmds:
      - go build -o {{.BIN_DIR}}/launcher.exe main.go
    env:
      GOOS: windows
      GOARCH: amd64

  test:
    summary: Runs tests
    cmds:
      - go test ./...

  clean:
    summary: Cleans build artifacts
    cmds:
      - rm -rf {{.BIN_DIR}}
